### ISSUE TITLE
a way to automatically re-enter symex mode from insert mode.

### ISSUE THREAD

**Issue by tommy-mor** [drym-org/symex.el#24]
Is there a setting I can put that binds escape in insert mode to go back to symex mode? It is annoying to have to press M-; so much.

Right now
```symex ---i---> insert mode ---esc---> normal mode ---M-;--> symex mode```
I want
```symex ---i---> insert mode ---esc---> symex mode```

**Comment by tommy-mor** [comment]
or is the design intended that you never enter insert mode. I think that's how lispy does it?

**Comment by tommy-mor** [comment]
@

**Comment by tommy-mor** [comment]
would this require rigpa? I guess what I want is my stack of layers to be this
```
normal mode
symex mode
insert mode
```
moving up the stack by pressing escape.

right now, I feel like symex is above normal

**Comment by tommy-mor** [comment]
I figured out how to do this.
```
(evil-define-key 'normal symex-mode-map
  (kbd "<escape>") 'symex-mode-interface)
```
Now whenever I am normal mode, I can toggle between normal mode and symex mode by pressing escape
So my tower of layers is more like
```
normal mode     <--esc-->      symex mode
|        ^
i       esc
v        |
insert mode
```

**Comment by countvajhula** [comment]
@tommy-mor Didn't get notified about this issue but that looks like a great way to do it!

You could also use rigpa for this, which gives you the flexibility to modify the behavior on the fly or even temporarily switch to a Vim-only tower (e.g. useful for editing comments, writing docstrings) so that you don't need to always have symex in the picture. But on the other hand, at the moment rigpa only supports towers as a way to structure the modes so you couldn't get exactly the behavior you have there. In the future the plan is to support other topologies, like rings or towers-of-rings, or directionally-variant structures like the one you've defined. And it would be recency aware so that you could alternate between the most recent modes. Can't say exactly when that will be implemented though, hopefully in the not-too-distant future.

**Comment by Garklein** [comment]
If anyone else comes across this issue, there's a current solution here: https://github.com/drym-org/symex.el/issues/164#issuecomment-3431456812
